# Site settings
title: Bastian Kroggel
email: mail@bastiankroggel.com
description: "There is currently no description, but I am working on it."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bastiankroggel.com" # the base hostname & protocol for your site
favicon: assets/img/favicon.png
theme-color: "#363636" #Theme color for Google Chrome for Android
twitter_username: derKroggel
github_username:  bkroggel

# Build settings
markdown: kramdown
