# Site settings
title: Bastian Kroggel
admin_user: Bastian Kroggel
year: 2016
email: mail@bastiankroggel.com
description: This is my personal website, where I post stuff that matters to me or might help you in different situations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bastiankroggel.com" # the base hostname & protocol for your site
favicon: /assets/img/site/favicon.png
theme-color: "#363636" #Theme color for Google Chrome for Android
twitter_username: derKroggel
github_username: bkroggel
excerpt_separator: <!-- more -->
highlighter: rouge

# Pagination Settings
paginate: 5
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown

#default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
